In [17]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('C:\Users\LENOVO\Downloads\flight_delay_cleaned.xls')
df

,distance_km,scheduled_hour,day_of_week,month,airline_rating,num_previous_delays,weather_severity_index,air_traffic_density,aircraft_age_years,wind_speed_kmh,precipitation_mm,temperature_c,visibility_km,runway_congestion_index,crew_rest_hours,departure_delay_minutes
0,1997.8,18,7,7,3.9,2,3.1,5.2,0.4,23.3,1.6,21.1,10.5,9.2,8.4,69.7
1,4763.4,7,2,10,5.0,1,6.1,6.7,23.0,12.0,0.9,29.5,9.4,9.0,10.3,139.3
2,3713.6,6,4,11,4.3,5,4.2,1.7,8.8,4.7,0.2,35.2,14.8,5.0,5.0,68.8
3,3073.6,15,5,1,3.2,1,9.4,6.0,2.5,39.3,3.7,19.5,13.7,6.9,9.5,119.5
4,948.9,18,6,1,2.9,6,9.6,8.7,19.0,3.4,2.3,10.4,6.2,3.2,12.0,101.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4507.5,0,6,10,3.9,2,5.9,3.1,7.9,4.6,1.5,14.2,14.9,4.1,12.0,85.5
4996,773.0,15,2,9,4.3,1,9.5,3.2,2.8,32.3,4.3,31.2,9.4,1.7,7.7,55.9
4997,1773.6,14,5,6,4.6,7,6.9,4.1,14.1,11.6,1.4,25.4,4.6,9.2,10.4,87.4
4998,4115.6,5,3,2,3.3,8,1.9,4.7,4.0,19.8,1.5,21.7,1.6,4.5,6.1,112.1
4999,3067.1,11,6,9,4.0,2,1.2,1.2,23.3,37.4,2.5,17.3,14.4,5.1,6.0,72.3

In [19]:
df.isna().sum()

distance_km                0
scheduled_hour             0
day_of_week                0
month                      0
airline_rating             0
num_previous_delays        0
weather_severity_index     0
air_traffic_density        0
aircraft_age_years         0
wind_speed_kmh             0
precipitation_mm           0
temperature_c              0
visibility_km              0
runway_congestion_index    0
crew_rest_hours            0
departure_delay_minutes    0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   distance_km              5000 non-null   float64
 1   scheduled_hour           5000 non-null   int64
 2   day_of_week              5000 non-null   int64
 3   month                    5000 non-null   int64
 4   airline_rating           5000 non-null   float64
 5   num_previous_delays      5000 non-null   int64
 6   weather_severity_index   5000 non-null   float64
 7   air_traffic_density      5000 non-null   float64
 8   aircraft_age_years       5000 non-null   float64
 9   wind_speed_kmh           5000 non-null   float64
 10  precipitation_mm         5000 non-null   float64
 11  temperature_c            5000 non-null   float64
 12  visibility_km            5000 non-null   float64
 13  runway_congestion_index  5000 non-null   float64
 14  crew_rest_hours          5000 non-null   float64
 15  departure_delay_minutes  5000 non-null   float64
dtypes: float64(12), int64(4)
memory usage: 625.1 KB

In [22]:
x = df.drop(['departure_delay_minutes'],axis=1)
y = df['departure_delay_minutes']
x

,distance_km,scheduled_hour,day_of_week,month,airline_rating,num_previous_delays,weather_severity_index,air_traffic_density,aircraft_age_years,wind_speed_kmh,precipitation_mm,temperature_c,visibility_km,runway_congestion_index,crew_rest_hours
0,1997.8,18,7,7,3.9,2,3.1,5.2,0.4,23.3,1.6,21.1,10.5,9.2,8.4
1,4763.4,7,2,10,5.0,1,6.1,6.7,23.0,12.0,0.9,29.5,9.4,9.0,10.3
2,3713.6,6,4,11,4.3,5,4.2,1.7,8.8,4.7,0.2,35.2,14.8,5.0,5.0
3,3073.6,15,5,1,3.2,1,9.4,6.0,2.5,39.3,3.7,19.5,13.7,6.9,9.5
4,948.9,18,6,1,2.9,6,9.6,8.7,19.0,3.4,2.3,10.4,6.2,3.2,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4507.5,0,6,10,3.9,2,5.9,3.1,7.9,4.6,1.5,14.2,14.9,4.1,12.0
4996,773.0,15,2,9,4.3,1,9.5,3.2,2.8,32.3,4.3,31.2,9.4,1.7,7.7
4997,1773.6,14,5,6,4.6,7,6.9,4.1,14.1,11.6,1.4,25.4,4.6,9.2,10.4
4998,4115.6,5,3,2,3.3,8,1.9,4.7,4.0,19.8,1.5,21.7,1.6,4.5,6.1
4999,3067.1,11,6,9,4.0,2,1.2,1.2,23.3,37.4,2.5,17.3,14.4,5.1,6.0

In [23]:
y

0        69.7
1       139.3
2        68.8
3       119.5
4       101.8
        ...
4995     85.5
4996     55.9
4997     87.4
4998    112.1
4999     72.3
Name: departure_delay_minutes, Length: 5000, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [32]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

predict_y1 = lr.predict(x_test)

from sklearn.metrics import r2_score , mean_squared_error

print(r2_score(y_test , predict_y1))
print(mean_squared_error(y_test , predict_y1))

0.9254947873602841
56.88937900474883

In [27]:
from sklearn.tree import DecisionTreeRegressor

dr = DecisionTreeRegressor()

dr.fit(x_train,y_train)

predict_y2 = dr.predict(x_test)

from sklearn.metrics import r2_score , mean_squared_error

print(r2_score(y_test , predict_y2))
print(mean_squared_error(y_test , predict_y2))

0.7414564678680249
197.41412

In [28]:
from sklearn.svm import SVR

svv = SVR()

svv.fit(x_train,y_train)

predict_y3 = svv.predict(x_test)

from sklearn.metrics import r2_score , mean_squared_error

print(r2_score(y_test , predict_y3))
print(mean_squared_error(y_test , predict_y3))

0.5737091007890349
325.499702265936

In [29]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(x_train, y_train)
predict_y4 = knn.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score

print(r2_score(y_test, predict_y4))
print(mean_squared_error(y_test, predict_y4))

0.5709876475941125
327.5777016

In [30]:
import joblib

joblib.dump(lr, 'flight_delay_model.pkl')

model = joblib.load('flight_delay_model.pkl')

In [44]:
predictions = model.predict(x_test)

In [45]:
df

,distance_km,scheduled_hour,day_of_week,month,airline_rating,num_previous_delays,weather_severity_index,air_traffic_density,aircraft_age_years,wind_speed_kmh,precipitation_mm,temperature_c,visibility_km,runway_congestion_index,crew_rest_hours,departure_delay_minutes
0,1997.8,18,7,7,3.9,2,3.1,5.2,0.4,23.3,1.6,21.1,10.5,9.2,8.4,69.7
1,4763.4,7,2,10,5.0,1,6.1,6.7,23.0,12.0,0.9,29.5,9.4,9.0,10.3,139.3
2,3713.6,6,4,11,4.3,5,4.2,1.7,8.8,4.7,0.2,35.2,14.8,5.0,5.0,68.8
3,3073.6,15,5,1,3.2,1,9.4,6.0,2.5,39.3,3.7,19.5,13.7,6.9,9.5,119.5
4,948.9,18,6,1,2.9,6,9.6,8.7,19.0,3.4,2.3,10.4,6.2,3.2,12.0,101.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4507.5,0,6,10,3.9,2,5.9,3.1,7.9,4.6,1.5,14.2,14.9,4.1,12.0,85.5
4996,773.0,15,2,9,4.3,1,9.5,3.2,2.8,32.3,4.3,31.2,9.4,1.7,7.7,55.9
4997,1773.6,14,5,6,4.6,7,6.9,4.1,14.1,11.6,1.4,25.4,4.6,9.2,10.4,87.4
4998,4115.6,5,3,2,3.3,8,1.9,4.7,4.0,19.8,1.5,21.7,1.6,4.5,6.1,112.1
4999,3067.1,11,6,9,4.0,2,1.2,1.2,23.3,37.4,2.5,17.3,14.4,5.1,6.0,72.3

In [43]:
new_flight = pd.DataFrame([{
    'distance_km': 40.0,
    'scheduled_hour': 4,
    'day_of_week': 3,
    'month': 7,
    'airline_rating': 4.2,
    'num_previous_delays': 3,
    'weather_severity_index': 5.5,
    'air_traffic_density': 1.0,
    'aircraft_age_years': 6.0,
    'wind_speed_kmh': 22.3,
    'precipitation_mm': 1.2,
    'temperature_c': 23.0,
    'visibility_km': 20.0,
    'runway_congestion_index': 5.5,
    'crew_rest_hours': 13.0
}])

delay_prediction = model.predict(new_flight)
print(f"Predicted delay: {delay_prediction[0]:.2f} minutes")

Predicted delay: 27.42 minutes